// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFEKIp1k4sTr7sC7uiJWOwyE6yKSh5TYs',
    appId: '1:210311762212:web:5ebe04ebbf717a7f91e3b1',
    messagingSenderId: '210311762212',
    projectId: 'bubbleovenauth',
    authDomain: 'bubbleovenauth.firebaseapp.com',
    storageBucket: 'bubbleovenauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBft0F7LaOC_qFNd6KIr6E9DdBSdRHiBck',
    appId: '1:210311762212:android:6115610500e7630391e3b1',
    messagingSenderId: '210311762212',
    projectId: 'bubbleovenauth',
    storageBucket: 'bubbleovenauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqqS-Nr-J5KBltyDifJm67JkD21R4TUSk',
    appId: '1:210311762212:ios:36171889700d667891e3b1',
    messagingSenderId: '210311762212',
    projectId: 'bubbleovenauth',
    storageBucket: 'bubbleovenauth.appspot.com',
    iosClientId: '210311762212-2celrvnqllbah49ur1kj55i5icqifd63.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleoven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqqS-Nr-J5KBltyDifJm67JkD21R4TUSk',
    appId: '1:210311762212:ios:36171889700d667891e3b1',
    messagingSenderId: '210311762212',
    projectId: 'bubbleovenauth',
    storageBucket: 'bubbleovenauth.appspot.com',
    iosClientId: '210311762212-2celrvnqllbah49ur1kj55i5icqifd63.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleoven',
  );
}
